version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_debug
    restart: always
    ports:
      - "8280:5432"
    environment:
      POSTGRES_DB: Teste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data_debug:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_debug:
